[package]
name = "zmanager-shell-extension"
version = "1.2.5"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
zmanager-shell-contract = { path = "../../crates/zmanager-shell-contract" }
windows = { version = "0.61.3", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_UI_Shell",
    "Win32_UI_Shell_Common",
] }
windows-core = "0.61.2"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"

